#!/usr/bin/env bash
# This script is for install nginx in server
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sudo sed -i "s/location \/ /location \/redirect_me /" /etc/nginx/sites-available/default
sudo sed -i "s/try_files \$uri \$uri\/ =404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4\/home;/" /etc/nginx/sites-available/default
service nginx start
