#!/usr/bin/env bash
# This script is for install nginx in server
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
new_line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "26i $new_line" /etc/nginx/sites-available/default
service nginx start
