#!/usr/bin/env bash
# This script is for install nginx in server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me http:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
service nginx start
