#!/usr/bin/env bash
# This script is for install nginx in server
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
