#!/usr/bin/env bash
# This script is for install nginx in server
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt update -y
sudo apt install -y haproxy
echo "frontend http_holb_front
    bind *:80
    mode http
    default_backend holb_back
    backend holb_back
    balance roundrobin
    server 1463-web-01 34.74.248.124:80 check
    server 1463-web-02 35.237.140.145:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
