#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
cnt=1
while [ $cnt -le 10 ]
do
	if [ $cnt = 9 ]
	then
		echo -e "Holberton School\nHi"
	else
		echo "Holberton School"
	fi
	cnt=$((cnt + 1))
done
